version: "3"
services:
  db:
    image: mysql
    # volumes:
    #   - ./db_backup/with_django_db_setup_v13.sql:/docker-entrypoint-initdb.d/with_django_db_setup.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: VandyIceHockey